--Dr. Sean Murthy
--Script to drop PVFC tables
--Run this script if you wish to undo any PVFC data you may already have
--This script can only drop tables in your dedicated schema

DROP TABLE IF EXISTS Uses_T CASCADE;
DROP TABLE IF EXISTS WorksIn_T CASCADE;
DROP TABLE IF EXISTS WorkCenter_T CASCADE;
DROP TABLE IF EXISTS DoesBusinessIn_T CASCADE;
DROP TABLE IF EXISTS EmployeeSkills_T CASCADE;
DROP TABLE IF EXISTS Supplies_T CASCADE;
DROP TABLE IF EXISTS ProducedIn_T CASCADE;
DROP TABLE IF EXISTS OrderLine_T CASCADE;
DROP TABLE IF EXISTS Product_T CASCADE;
DROP TABLE IF EXISTS ProductLine_T CASCADE;
DROP TABLE IF EXISTS Order_T CASCADE;
DROP TABLE IF EXISTS Salesperson_T CASCADE;
DROP TABLE IF EXISTS Vendor_T CASCADE;
DROP TABLE IF EXISTS Skill_T CASCADE;
DROP TABLE IF EXISTS RawMaterial_T CASCADE;
DROP TABLE IF EXISTS Territory_T CASCADE;
DROP TABLE IF EXISTS Employee_T CASCADE;
DROP TABLE IF EXISTS Customer_T CASCADE;
